
export const styles = {
    appShell: {
        width: '100%',
        maxWidth: '520px',
        minHeight: '100dvh',
        display: 'grid',
        gridTemplateRows: 'auto 1fr auto',
        gap: '12px',
        padding: '12px',
        background: 'repeating-linear-gradient(0deg, #1b1f28, #1b1f28 4px, #171a22 4px, #171a22 8px)',
        fontFamily: '"VT323", monospace',
        color: '#e5e5e5',
    },
    panel: {
        background: '#222734',
        border: '4px solid #2b3242',
        boxShadow: '0 0 0 4px #0b0d12 inset, 0 6px 0 0 #0b0d12',
        borderRadius: '8px',
    },
    header: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: '16px 16px',
        background: '#222734',
        border: '2px solid #2b3242',
        boxShadow: '0 0 0 4px #0b0d12 inset, 0 6px 0 0 #0b0d12',
        borderRadius: '5px',
        flexWrap: 'wrap',
        gap: '8px',
    },
    title: {
        fontFamily: '"Press Start 2P", monospace',
        fontSize: 'clamp(14px, 4vw, 18px)',
        margin: 0,
        textTransform: 'uppercase',
    },
    countChip: {
        background: '#2b3242',
        border: '4px solid #0b0d12',
        borderRadius: '8px',
        padding: '8px 12px',
        fontFamily: '"Press Start 2P", monospace',
        fontSize: 'clamp(10px, 2.5vw, 12px)',
    },
    toolbar: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        padding: '12px',
    },
    field: {
        display: 'flex',
        gap: '8px',
        width: '100%',
    },
    input: {
        flex: 1,
        background: '#2b3242',
        color: '#e5e5e5',
        border: '4px solid #0b0d12',
        borderRadius: '8px',
        padding: '14px 12px',
        fontFamily: '"VT323", monospace',
        fontSize: '20px',
        outline: 'none',
        minWidth: 0,
    },
    editInput: {
        flex: 1,
        background: '#2b3242',
        color: '#e5e5e5',
        border: '2px solid #66ffc4',
        borderRadius: '6px',
        padding: '8px',
        fontFamily: '"VT323", monospace',
        fontSize: '20px',
        outline: 'none',
    },
    btnPrimary: {
        background: '#66ffc4',
        color: '#121418',
        border: '4px solid #0b0d12',
        borderRadius: '8px',
        padding: '14px 18px',
        fontFamily: '"Press Start 2P", monospace',
        fontSize: '16px',
        cursor: 'pointer',
        fontWeight: 'bold',
        flexShrink: 0,
    },
    btnSecondary: {
        background: '#ffd166',
        color: '#121418',
        border: '4px solid #0b0d12',
        borderRadius: '8px',
        padding: '10px 14px',
        fontFamily: '"Press Start 2P", monospace',
        fontSize: '10px',
        cursor: 'pointer',
        textTransform: 'uppercase',
    },
    btnDanger: {
        background: '#ff6b6b',
        color: '#fff',
        border: '4px solid #0b0d12',
        borderRadius: '8px',
        padding: '10px 14px',
        fontFamily: '"Press Start 2P", monospace',
        fontSize: '10px',
        cursor: 'pointer',
        textTransform: 'uppercase',
    },
    btnActive: {
        boxShadow: '0 3px 0 0 #0b0d12 inset',
        transform: 'translateY(2px)',
    },
    list: {
        display: 'flex',
        flexDirection: 'column',
        gap: '10px',
        padding: '12px',
        maxHeight: '60vh',
        overflowY: 'auto',
    },
    item: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
        background: '#2b3242',
        border: '4px solid #0b0d12',
        borderRadius: '8px',
        padding: '12px',
        borderLeft: '8px solid',
    },
    itemMain: {
        display: 'flex',
        alignItems: 'center',
        gap: '10px',
    },
    checkbox: {
        width: '28px',
        height: '28px',
        flexShrink: 0,
        appearance: 'none',
        background: '#0f1116',
        border: '4px solid #0b0d12',
        borderRadius: '6px',
        position: 'relative',
        cursor: 'pointer',
    },
    todoText: {
        flex: 1,
        fontFamily: '"VT323", monospace',
        fontSize: '22px',
        wordBreak: 'break-word',
        cursor: 'pointer',
        minWidth: 0,
    },
    todoTextDone: {
        textDecoration: 'line-through',
        color: '#9aa1ac',
    },
    prioBtn: {
        width: '36px',
        height: '36px',
        flexShrink: 0,
        border: '4px solid #0b0d12',
        borderRadius: '8px',
        fontFamily: '"Press Start 2P", monospace',
        fontSize: '12px',
        cursor: 'pointer',
        color: '#121418',
        fontWeight: 'bold',
    },
    actions: {
        display: 'flex',
        gap: '8px',
        paddingTop: '4px',
    },
    footer: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: '8px',
        padding: '12px',
        background: '#222734',
        border: '4px solid #2b3242',
        boxShadow: '0 0 0 4px #0b0d12 inset, 0 6px 0 0 #0b0d12',
        borderRadius: '8px',
        flexWrap: 'wrap',
    },
    filter: {
        display: 'flex',
        gap: '6px',
        flexWrap: 'wrap',
    },
    empty: {
        textAlign: 'center',
        padding: '24px 12px',
        color: '#9aa1ac',
        fontFamily: '"VT323", monospace',
        fontSize: '20px',
    },
}